(add-to-list 'load-path "~/.emacs.d")
(require 'smart-compile)
(global-set-key [f5] 'smart-compile)
(global-set-key [(C-f5)] 'recompile)
(global-set-key [f6] 'shell)
(global-set-key [f7] 'shell-command)
